options:
  node-version:
    default: '5.x'
    description: |
      NodeJS Version to use for your application. Supported versions are
      0.10, 0.12, 4.x, 5.x
    type: string
  node-application-dir:
    type: string
    default: 'dist'
    description: |
      The default location of your Node.js application, defaults $CHARM_DIR/dist
